# Generated by Django 2.2 on 2019-06-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='album',
            name='album_title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='song',
            name='song_title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='song',
            name='title_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
